### ISSUE TITLE
Poor results for OpenAI GPT model (NER)

### ISSUE THREAD

**Issue by stefan-it** [nelson-liu/contextual-repr-analysis#3] opened 2019-03-23 20:35 UTC
Hi @nelson-liu,

I just read the appendix of the paper and noticed the bad performance of the GPT model for NER.

I made some experiments with the `pytorch_pretrained_bert` implementation (in combination with `flair`) to get embeddings for each token in a sentence to train a model (see this [PR](https://github.com/zalandoresearch/flair/pull/624)).

The results are pretty good (81.67%) on the CoNLL-2003 dataset.

I found the `generate_openai_transformer_embeddings.py` script that uses the internal GPT model implementation of `allennlp`.

Is there any chance that you could try to use `pytorch_pretrained_bert` implementation to retrieve the embeddings? I'm just wondering why there's a difference of ~30% compared to the other models.

**Comment by nelson-liu** [comment] 2019-03-24 01:18
Interesting, I'll try to run these before the camera-ready deadline and keep you updated of the results.

In the allennlp OpenAI model, the embeddings for a token are taken to be its `last` BPE embedding. Is there any chance you can run that experiment in the near future and see if it explains the ~30% drop (I noticed that you only tried first, first+last, and meanpool)?

**Comment by stefan-it** [comment] 2019-03-24 10:06
@nelson-liu No problem, experiment with using only the last subword is currently running! I will report back here as soon it has finished :)

**Comment by nelson-liu** [comment] 2019-03-24 14:44
I also ran a sanity check with just vanilla allennlp, to conclusively rule out that the bug is in this codebase.

I modified the simple tagger like so:

```diff
diff --git a/allennlp/models/simple_tagger.py b/allennlp/models/simple_tagger.py
index 0a1cf29..c933fba 100644
--- a/allennlp/models/simple_tagger.py
+++ b/allennlp/models/simple_tagger.py
@@ -12,7 +12,7 @@ from allennlp.modules import Seq2SeqEncoder, TimeDistributed, TextFieldEmbedder
 from allennlp.models.model import Model
 from allennlp.nn import InitializerApplicator, RegularizerApplicator
 from allennlp.nn.util import get_text_field_mask, sequence_cross_entropy_with_logits
-from allennlp.training.metrics import CategoricalAccuracy
+from allennlp.training.metrics import CategoricalAccuracy, SpanBasedF1Measure


 @Model.register("simple_tagger")
@@ -55,6 +55,7 @@ class SimpleTagger(Model):
                 "accuracy": CategoricalAccuracy(),
                 "accuracy3": CategoricalAccuracy(top_k=3)
         }
+        self.f1 = SpanBasedF1Measure(vocab, "labels", "IOB1")

         initializer(self)

@@ -113,6 +114,7 @@ class SimpleTagger(Model):
             for metric in self.metrics.values():
                 metric(logits, tags, mask.float())
             output_dict["loss"] = loss
+        self.f1(logits, tags, mask.float())

         if metadata is not None:
             output_dict["words"] = [x["words"] for x in metadata]
@@ -141,4 +143,7 @@ class SimpleTagger(Model):

     @overrides
     def get_metrics(self, reset: bool = False) -> Dict[str, float]:
-        return {metric_name: metric.get_metric(reset) for metric_name, metric in self.metrics.items()}
+        metrics_dict = {metric_name: metric.get_metric(reset) for metric_name, metric in self.metrics.items()}
+        f1_dict = self.f1.get_metric(reset=reset)
+        metrics_dict.update(f1_dict)
+        return metrics_dict
```

Then, I trained with the following config:

```json
{
  "dataset_reader": {
      "type": "conll2003",
      "tag_label": "ner",
      "token_indexers": {
        "tokens": {
          "type": "single_id"
        },
        "openai_transformer": {
            "type": "openai_transformer_byte_pair",
            "model_path": "https://s3-us-west-2.amazonaws.com/allennlp/models/openai-transformer-lm-2018.07.23.tar.gz"
        },
      }
  },
  "train_data_path": "/path/to/eng.train",
  "validation_data_path": "/path/to/eng.testa",
  "test_data_path": "/path/to/eng.testb",
  "evaluate_on_test": true,
  "model": {
    "type": "simple_tagger",
    "text_field_embedder": {
        "allow_unmatched_keys": true,
        "embedder_to_indexer_map": {
            "openai_transformer": ["openai_transformer", "openai_transformer-offsets"]
        },
        "token_embedders": {
            "openai_transformer": {
                "type": "openai_transformer_embedder",
                "transformer": {
                    "model_path": "https://s3-us-west-2.amazonaws.com/allennlp/models/openai-transformer-lm-2018.07.23.tar.gz"
                },
            }
        }
    },
    "encoder": {
      "type": "pass_through",
      "input_dim": 768
    }
  },
  "iterator": {
    "type": "basic",
    "batch_size": 80
  },
  "trainer": {
    "optimizer": "adam",
    "num_epochs": 50,
    "patience": 3,
    "cuda_device": 0,
    "validation_metric": "+f1-measure-overall",
    "num_serialized_models_to_keep": 3
  }
}
```

This reruns the scalar mix experiment for the openai gpt model on ner (embeddings + linear layer).

The final output looks like:

```
{
  "peak_cpu_memory_MB": 3075.172,
  "peak_gpu_0_memory_MB": 6837,
  "peak_gpu_1_memory_MB": 10,
  "training_duration": "01:06:34",
  "training_start_epoch": 0,
  "training_epochs": 9,
  "epoch": 9,
  "training_accuracy": 0.9367403165685269,
  "training_accuracy3": 0.9916266003997622,
  "training_precision-ORG": 0.4035247645092677,
  "training_recall-ORG": 0.42018667932289194,
  "training_f1-measure-ORG": 0.4116872045260292,
  "training_precision-LOC": 0.6542999773088268,
  "training_recall-LOC": 0.807703081232493,
  "training_f1-measure-LOC": 0.7229534912874019,
  "training_precision-PER": 0.704056590154468,
  "training_recall-PER": 0.7389393939393939,
  "training_f1-measure-PER": 0.7210763657868947,
  "training_precision-MISC": 0.576681020205366,
  "training_recall-MISC": 0.5063990692262944,
  "training_f1-measure-MISC": 0.5392597181353073,
  "training_precision-overall": 0.5935206376765844,
  "training_recall-overall": 0.6400697902038385,
  "training_f1-measure-overall": 0.6159169550172512,
  "training_loss": 0.23204569247635928,
  "training_cpu_memory_MB": 3075.172,
  "training_gpu_0_memory_MB": 6837,
  "training_gpu_1_memory_MB": 10,
  "validation_accuracy": 0.9390210661578599,
  "validation_accuracy3": 0.9917448697480628,
  "validation_precision-ORG": 0.3939393939393939,
  "validation_recall-ORG": 0.4168530947054437,
  "validation_f1-measure-ORG": 0.40507246376806594,
  "validation_precision-LOC": 0.6396588486140725,
  "validation_recall-LOC": 0.8165487207403375,
  "validation_f1-measure-LOC": 0.7173601147775692,
  "validation_precision-PER": 0.753475935828877,
  "validation_recall-PER": 0.7649294245385451,
  "validation_f1-measure-PER": 0.7591594827585706,
  "validation_precision-MISC": 0.5980861244019138,
  "validation_recall-MISC": 0.5422993492407808,
  "validation_f1-measure-MISC": 0.5688282138793584,
  "validation_precision-overall": 0.6132921174652242,
  "validation_recall-overall": 0.6677886233591384,
  "validation_f1-measure-overall": 0.6393812439574107,
  "validation_loss": 0.22605512936304256,
  "best_epoch": 7,
  "best_validation_accuracy": 0.9389821268642187,
  "best_validation_accuracy3": 0.9914917643393949,
  "best_validation_precision-ORG": 0.42749371332774516,
  "best_validation_recall-ORG": 0.38031319910514544,
  "best_validation_f1-measure-ORG": 0.4025256511443859,
  "best_validation_precision-LOC": 0.6433203631647212,
  "best_validation_recall-LOC": 0.8100163309744148,
  "best_validation_f1-measure-LOC": 0.7171084337348905,
  "best_validation_precision-PER": 0.7496167603474706,
  "best_validation_recall-PER": 0.7964169381107492,
  "best_validation_f1-measure-PER": 0.7723085022373811,
  "best_validation_precision-MISC": 0.595797280593325,
  "best_validation_recall-MISC": 0.5227765726681127,
  "best_validation_f1-measure-MISC": 0.5569035239745314,
  "best_validation_precision-overall": 0.6293048469387755,
  "best_validation_recall-overall": 0.6642544597778526,
  "best_validation_f1-measure-overall": 0.6463075159652357,
  "best_validation_loss": 0.22923851549261953,
  "test_accuracy": 0.9291698072574567,
  "test_accuracy3": 0.9887800150748358,
  "test_precision-LOC": 0.5676369863013698,
  "test_recall-LOC": 0.7949640287769785,
  "test_f1-measure-LOC": 0.6623376623376138,
  "test_precision-ORG": 0.3955491744436468,
  "test_recall-ORG": 0.3317278747742324,
  "test_f1-measure-ORG": 0.3608382449246393,
  "test_precision-MISC": 0.49572649572649563,
  "test_recall-MISC": 0.49572649572649563,
  "test_f1-measure-MISC": 0.4957264957264456,
  "test_precision-PER": 0.7130281690140845,
  "test_recall-PER": 0.75139146567718,
  "test_f1-measure-PER": 0.7317073170731208,
  "test_precision-overall": 0.560717196414018,
  "test_recall-overall": 0.6090651558073654,
  "test_f1-measure-overall": 0.5838920478655192,
  "test_loss": 0.2714051358740438
}
```

Note that `"test_f1-measure-overall": 0.5838920478655192`, which is quite comparable to what was in the paper.

Given these results, it seems like either:
1) There's a bug in the AllenNLP OpenAIGPT
2) Using the last BPE embedding is just a poor strategy. I don't think I've seen any literature that discusses what the best pooling strategy for BPE-vocab language model embeddings is. `last` might work poorly because the BPE representations from the transformer have no incentive to encode information about the current token---the representation is purely optimized for predicting the next word.

Hopefully your experiment with the `last` embedding also shows the same result, since that would suggest that 2) is the cause for the drop.

**Comment by matt-gardner** [comment] 2019-03-24 15:34
Sorry if this is a naive question, @stefan-it, but it's not obvious to me whether the embeddings in the PR you referenced are fine tuned or not.  Are you sure they are fixed during training?

**Comment by matt-gardner** [comment] 2019-03-24 15:35
And @nelson-liu, the OpenAI GPT code in AllenNLP was just copied from the initial huggingface codebase (this was before they had BERT and pip releases).  I'm pretty sure we've replicated several things there, and I'd be quite surprised if this difference was due to a bug in that code (though I've been surprised before...).

**Comment by stefan-it** [comment] 2019-03-24 18:59
@nelson-liu and @matt-gardner thanks for your replies!

The final F1-score is 81.38% when using only the last subword. After one training epoch the F1-score was 67.49%. Embeddings are fixed during training.

**Comment by nelson-liu** [comment] 2019-03-25 00:27
@stefan-it i ran the experiment with the first BPE embedding, and I got a very similar result as above (~59 F1). I think i know what's wrong: in the code snippet of your PR, your probing model seems to be some sort of MLP with a CRF on top? The experiments in the paper and appendix only use a linear probing layer (unless otherwise specified). 

We did try using a larger probe for NER and we saw a similar gain in performance; we then dug into why the linear model does poorly. See Table 2 / the `Probing Failures` paragraph of section 4.2 .

Can you confirm that you're training a MLP + CRF on top of the frozen embeddings? If so, then I think this issue can be closed---that would totally explain the difference.

Thanks!

**Comment by stefan-it** [comment] 2019-03-25 08:56
@nelson-liu yes, the architecture is a BiLSTM with a CRF on top -> sorry for the circumstances!

**Comment by nelson-liu** [comment] 2019-03-25 10:54
ah ok, no worries! thanks for raising the issue regardless, i appreciate it! closing this now...

**Closed as completed by nelson-liu** 2019-03-25 10:54 UTC
